window.SENTENCES_AUDIO_MAP = {
  "Letter ai. Sound a. Find the word that starts with ai.": "assets/audios/sentences/frog_prompt_ai.mp3",
  "Letter ai. Sound /a/. Find the word that starts with ai.": "assets/audios/sentences/frog_prompt_ai.mp3",
  "Letter ai. Find the word that starts with ai": "assets/audios/sentences/frog_intro_ai.mp3",
  "Letter oi. Sound o. Find the word that starts with oi.": "assets/audios/sentences/frog_prompt_oi.mp3",
  "Letter oi. Sound /o/. Find the word that starts with oi.": "assets/audios/sentences/frog_prompt_oi.mp3",
  "Letter oi. Find the word that starts with oi": "assets/audios/sentences/frog_intro_oi.mp3",
  "Letter air. Sound a. Find the word that starts with air.": "assets/audios/sentences/frog_prompt_air.mp3",
  "Letter air. Sound /a/. Find the word that starts with air.": "assets/audios/sentences/frog_prompt_air.mp3",
  "Letter air. Find the word that starts with air": "assets/audios/sentences/frog_intro_air.mp3",
  "Letter oy. Sound o. Find the word that starts with oy.": "assets/audios/sentences/frog_prompt_oy.mp3",
  "Letter oy. Sound /o/. Find the word that starts with oy.": "assets/audios/sentences/frog_prompt_oy.mp3",
  "Letter oy. Find the word that starts with oy": "assets/audios/sentences/frog_intro_oy.mp3",
  "What do you point to on your face? Point to your nose and touch your ear!": "assets/audios/sentences/frog_act_e75b2c9b.mp3",
  "Point to your nose and touch your ear! What do you point to on your face?": "assets/audios/sentences/frog_act_e75b2c9b.mp3",
  "What do you raise? Raise your left arm and clap your hands.": "assets/audios/sentences/frog_act_3173848f.mp3",
  "Raise your left arm and clap your hands. What do you raise?": "assets/audios/sentences/frog_act_3173848f.mp3",
  "What can fly high in the air? The silver airplane can fly high in the air.": "assets/audios/sentences/frog_act_cc83d7f8.mp3",
  "The silver airplane can fly high in the air. What can fly high in the air?": "assets/audios/sentences/frog_act_cc83d7f8.mp3",
  "What does the boy play with? The happy boy plays with his new colorful toy.": "assets/audios/sentences/frog_act_2a3007b9.mp3",
  "The happy boy plays with his new colorful toy. What does the boy play with?": "assets/audios/sentences/frog_act_2a3007b9.mp3",
  "What vehicle runs on the track? Look at the silver train running on the track.": "assets/audios/sentences/frog_act_b202c337.mp3",
  "Look at the silver train running on the track. What vehicle runs on the track?": "assets/audios/sentences/frog_act_b202c337.mp3"
};
